# Properties configuration

camel:
  springboot:
    # The Camel context name
    name: CamelApolicesRest

  component:
    servlet:
      mapping:
        contextPath: /apolices/*

mysql:
  service:
  host: localhost
  port: 3306
  database: db_apolices
  username: root
  password: root
  #driverclass: com.mysql.cj.jdbc.Driver
   
spring:
  # Spring JDBC configuration
  datasource:
    #url:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}
    jdbcUrl:   jdbc:mysql://localhost:3306/db_apolices?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    

server:
  port: 8080
  
management:
  port: 8081
  
endpoints:
  enabled: false
  health:
    enabled: true
    
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s